### ISSUE TITLE
이슈 대응

### ISSUE THREAD

**Issue by unam98** [Runnect/Runnect-Android#124]
## 💡 Issue

누락됐거나 이슈가 발견될 때마다 여기에다 추가해놓고 하나씩 해결해나갈 예정

## 📝 todo

- [ ] 방문자모드- 스크랩 상세페이지에서 스크랩 기능 안 막아놓음
- [ ] 방문자모드 - 러닝 시작하기 이후 logic이 그대로 허용되고있음 막아놔야 함
- [ ] 방문자모드 - 스크랩에서 업로드 버튼 누를 때랑 하트 누를 때랑 토스트 메세지 문구 다름
- [ ] 토스트 메세지 위치 조절하려면 커스텀으로 직접 만들어야 함 
- [ ] 코스발견 - 하트 크기 키우기
