### ISSUE TITLE
방문자모드 러닝 금지

### ISSUE THREAD

**Issue by unam98** [Runnect/Runnect-Android#125]
## 💡 Issue

방문자모드 진입 시 러닝 기능이 동작하면 안 되는데 허용되고 있음 막으려고 함
## 📝 todo

- [x] 방문자모드 러닝 금지
- [x] 스크랩 하트 크기 키우기
- [x] 토스트 메세지 문구 다르게 하기
- [x] 토스트 메세지 위치 조절 (커스텀 토스트)
- [x] 스크랩 상세페이지에서 스크랩 기능 막기
