### ISSUE TITLE
[Ui] 구분선 색상 변경

### ISSUE THREAD

**Issue by Larry7939** [Runnect/Runnect-Android#140]
## 💡 Issue

구분선 색상 변경
## 📝 todo

- [ ] 러닝 기록 상세 뷰 구분선
- [ ] 마이페이지 각 항목 프레임 밑 구분선
- [ ] 설정 뷰 툴바 및 항목 구분선
