### ISSUE TITLE
비효율적인 코드 개선

### ISSUE THREAD

**Issue by unam98** [Runnect/Runnect-Android#167]
## 💡 Issue

불필요하게 코드를 길게 썼거나 data class를 하나만 써도 되는데 2개,3개로 나뉘어 있는 등 비효율적인 부분이 있는데 이를 개선하고자 함
## 📝 todo

- [x] CountDownActivity data 수신 코드 수정
- [x] customDialog를 확장함수로 빼주어 재사용성 높이기 및 보일러 플레이트 코드 줄이기
- [x] named arguments 적용
- [x] CountToRunData 등 불필요한 data class 삭제
- [x] dto 폴더 통일
