### ISSUE TITLE
firebase 코드 리팩토링

### ISSUE THREAD

**Issue by unam98** [Runnect/Runnect-Android#170]
## 💡 Issue

통신 코드 리팩토링 이전의 develop에서 브랜치를 팠기 때문에 당장 구조적인 걸 건드리면 추후 merge할 때 conflict가 너무 많이 날 것 같아서 일단 merge 했습니다. 이번 branch에서는 미처 마무리 못했던 작업들을 마저 해주려고 합니다.

addSnapshotListener로 변경 사항이 있을 시 data를 실시간으로 수신해오지만 이걸 화면에 바로 바인딩되게 하는 것은 별개의 문제입니다. 갱신된 data들을 adapter에 submitList를 해주는 코드가 현재 없는 상황이므로 이 작업을 추가할 것입니다.

관심사 분리를 위해 firebase 코드를 fragment에서 분리할 것입니다. 

## 📝 todo

- [x] data 갱신 시 ui도 바로 갱신되게 할 것 
- [x] firebase 코드를 fragment에서 분리하여 관심사를 분리할 것
- [x] timer 초기화 문제 해결
