### ISSUE TITLE
Topic

### ISSUE THREAD

**Issue by unam98** [Runnect/Runnect-Android#171]
## 💡 Issue

추후 같이 얘기 나눠봐야 할 것들 리스트업
## 📝 todo

- [ ] data class 네이밍, 폴더링 
- [x] 이미지 바인딩할 때 Adapter에서 직접 세팅해줄 건지, BindingAdapter에 fun 만들어서 xml 상에서 처리할 것인지
- [ ] kakao_strings.xml -> local.properties로 이전
- [ ] presentaion 폴더 안에 들어있는 하위 폴더들 네이밍 수정

**Comment by unam98** [comment]
Discussions 탭으로 이전
