### ISSUE TITLE
[Feature] 마이페이지-서버연결

### ISSUE THREAD

**Issue by Larry7939** [Runnect/Runnect-Android#20]
## 💡 Issue

![image](https://user-images.githubusercontent.com/70442964/211381968-9b8557e3-fb90-4ce8-9e4f-3b41b2422c73.png)

## 📝 todo

- [x] getUser - 마이페이지(유저정보 보여주기)
- [x] updateUserNickname - 닉네임 변경
- [x] getStampByUser - 유저 목표보상(유저가 받은 스탬프)
- [x] getRecordByUser - 유저 활동 기록
- [x] getPublicCourseByUser - 유저가 업로드한 코스
