### ISSUE TITLE
[Feature] 코스발견-서버연결

### ISSUE THREAD

**Issue by Larry7939** [Runnect/Runnect-Android#21]
## 💡 Issue

![image](https://user-images.githubusercontent.com/70442964/211821894-e5c2cdad-186a-45a8-bc0d-68d9af0bd11c.png)

## 📝 todo

- [x] recommendPublicCourse - 이런 코스는 어때요?
- [x] createAndDeleteScrap - 코스 스크랩, 스크랩 취소
- [x] searchPublicCourse - 코스 검색
- [x] getPublicCourseDetail - 스크랩코스(업로드된 코스) 상세 페이지
- [x] getPrivateCourseByUser - 내가 그린 코스(업로드 미포함) -> 불러오기 뷰
- [x] createPublicCourse - 내가 그린 코스 업로드하기

**Comment by dlwogus0128** [comment]
들렀다갑니다.. 같은 클라끼리 의지해요 ㅋ

**Comment by Larry7939** [comment]
> 들렀다갑니다.. 같은 클라끼리 의지해요 ㅋ
반가워요 ㅋ
