### ISSUE TITLE
[UI] 마이페이지 / UI 수정 사항 반영

### ISSUE THREAD

**Issue by unam98** [Runnect/Runnect-Android#230]
## 💡 Issue

마이페이지 UI 변경 사항을 반영합니다.

## 📝 todo

- [x] 러닝기록, 목표보상 버튼 순서 변경 
- [x] 뒤로가기 애니메이션 통일 (닉네임 수정 화면 제외)  
- [x] 유저 프로필, 레벨 프로그레스바 배경 색상 변경 
- [x] 수정하기 버튼 색상 변경 
- [x] 닉네임 수정 화면에서 뷰의 위치 변경
