### ISSUE TITLE
[MOD] 마이페이지 / 러닝기록 수정 & 삭제 팝업 메뉴 

### ISSUE THREAD

**Issue by unam98** [Runnect/Runnect-Android#231]
## 💡 Issue

- 코스 상세페이지 더보기 버튼 클릭 시, 바텀시트 대신 팝업 메뉴가 뜨도록 변경합니다. 
- 마이페이지 러닝기록 상세페이지에 먼저 적용하고, 다른 상세 페이지에도 순차적으로 적용할 예정입니다. 

## 📝 todo

- [x] 커스텀 팝업 메뉴 구현 
- [x] 바텀시트 대신에 팝업메뉴가 뜨도록 변경 
- [x] 마이페이지 러닝기록 제목 수정하기 
- [x] 마이페이지 러닝기록 삭제하기 
- [x] 에디트텍스트 커서 색상 변경 
- [x] 수정하기 버튼 누르면 바로 키패드가 올라오도록 
- [x] 기존 코드 전반적으로 리팩토링: [노션 참고](https://www.notion.so/runnectiosonboarding/fd3b18700e334f33a78c3a075b8ca4ca?pvs=4)
