### ISSUE TITLE
[FIX] 코스 발견 / 상세페이지에서 스크랩 하면 이전 화면에도 바로 반영되도록 변경

### ISSUE THREAD

**Issue by leeeha** [Runnect/Runnect-Android#246]
## 💡 Issue

- 상세페이지에서 스크랩 하면, 이전 화면에도 바로 반영되도록 변경 

## 📝 todo

- [ ] 기존의 무한 스크롤 코드 이해하기 
- [ ] NestedScrollView + scrollListener -> ConcatAdapter + Paging (대규모 리팩토링 예상) 
- [ ] 상세페이지에서의 스크랩 여부를 sharedPreferences에 저장 -> 이전 화면으로 돌아왔을 때 반영 (해당 아이템만 갱신)
