### ISSUE TITLE
[REFACTOR] 코스 상세페이지 / 전면 리팩토링  

### ISSUE THREAD

**Issue by leeeha** [Runnect/Runnect-Android#267]
## 💡 Issue

코스 상세페이지 관련 코드를 전면 리팩토링 합니다.

## 📝 todo

- [x] 자신이 업로드한 코스 수정/삭제 시, 바텀시트 대신 팝업메뉴 뜨도록 변경 
- [x] 자신의 코스는 수정/삭제, 다른 사람 코스는 신고하기 팝업 뜨도록 구분
- [x] 하드코딩한 문자열 리소스화 
- [x] 코스 상세페이지 조회/수정/삭제에 대한 서버통신 코드 수정 (BaseResponse, UiStateV2 사용하도록) 
- [x] 내용 수정하다가 중간에 뒤로가기 누르는 경우, 작성 중단 확인 다이얼로그 띄우기 
- [x] kotlin-android-extensions (deprecated) 사용하는 다이얼로그 걷어내기 (데이터 바인딩 사용) 
- [x] 코스 상세페이지의 이전 화면들을 문자열 대신 enum class로 구분하기 
- [x] 리팩토링 후 발생하는 각종 버그 해결하기 

---

브랜치 사이즈가 너무 커지기 때문에, 아래 내용들은 다른 브랜치에서 따로 작업하겠습니다!! 

- [ ] 코스 상세페이지에서 이전 화면으로 돌아갔을 때, 수정 & 삭제한 아이템 내용이 뷰에 바로 반영되도록
- [ ] 러닝기록 아이템 선택은 되는데 삭제하기 버튼이 활성화 되지 않는 이슈 해결하기 
- [ ] 코스 스크랩하는 서버통신 코드 수정하기 (불필요한 블록 삭제)
