### ISSUE TITLE
[Refactor] 코드 병합

### ISSUE THREAD

**Issue by Larry7939** [Runnect/Runnect-Android#27]
## 💡 Issue

코스달리기 + 마이페이지,코스추천
## 📝 todo

- [x] key/url/id 숨기기
- [x] 단일 Activity 구조 만들기
- [x] 달리기 시작 기능 연결
