### ISSUE TITLE
[REFACTOR] 코스 발견 / 전면 리팩토링 

### ISSUE THREAD

**Issue by leeeha** [Runnect/Runnect-Android#282]
## 💡 Issue

코스발견 페이지를 리팩토링 합니다. 

## 📝 todo

- [x] 그리드 레이아웃 아이템 데코레이션에 named argument 적용 
- [x] 서버 요청, 응답 DTO 네이밍 통일성 있게 변경 
- [x] 리사이클러뷰 아이템 클릭리스너 네이밍 통일성 있게 변경 
- [x] 하드코딩 한 문자열 -> string 리소스 사용하도록 변경 
- [x] 변수, 함수 이름 더 가독성 있게 변경 
- [x] 바인딩 어댑터 적용 
- [x] UI 레이어에서 Data Layer DTO 대신 Domain Layer Entity 사용하도록 변경 
- [X] RecyclerView in NestedScrollView -> 중첩 리사이클러뷰 + 멀티뷰 타입 
- [X] 프로모션 배너 뷰페이저 -> CollapsingToolbarLayout 사용하도록 변경 
- [x] UiStateV2 적용 (배너, 마라톤, 추천 코스 조회) 
- [x] 스크롤에 따라 업로드 버튼 모양 변경되도록
