### ISSUE TITLE
[REFACTOR] kotlin-android-extensions -> 뷰 바인딩 

### ISSUE THREAD

**Issue by leeeha** [Runnect/Runnect-Android#285]
## 💡 Issue

>The 'kotlin-android-extensions' Gradle plugin is deprecated.
Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

위의 경고를 해결하기 위한 마이그레이션 작업을 진행합니다. 

## 📝 todo

마이그레이션 작업을 통해 아래 에러들을 해결할 예정입니다. 

- [x] DrawActivity (코스 그리기 완료)
- [x] MyDrawDetailActivity (내가 그린 코스 삭제)
- [x] MyHistoryActivity (러닝기록 삭제) 
- [x] MyUploadActivity (업로드한 코스 삭제)
- [x] StorageMyDrawFragment (편집 모드에서 내가 그린 코스 삭제) 
- [x] MySettingAccountInfoFragment (로그아웃, 회원탈퇴) 
- [x] ContextExt 
- [x] model, entity 의 android-parcelize -> kotlinx.parcelize 로 변경

<img width="400" src="https://github.com/Runnect/Runnect-Android/assets/68090939/c6cc7183-cc94-4314-8cac-25ee8a239085"/> 

<img width="350" src="https://github.com/Runnect/Runnect-Android/assets/68090939/e98be18c-f975-4c05-8e84-b2e6cea68343"/>
