### ISSUE TITLE
[REFACTOR] 코스 발견 / 프로모션 배너 뷰페이저 애니메이션 

### ISSUE THREAD

**Issue by leeeha** [Runnect/Runnect-Android#286]
## 💡 Issue

- 일정 시간 간격으로 뷰페이저가 자동으로 스와이프 되는 기능과 관련된 코드를 리팩토링 합니다. 

## 📝 todo

- [x] 뷰페이저 무한 스크롤 
- [x] 인디케이터 같이 움직이도록 
- [x] 뷰페이저 스크롤 상태에 따라 Job 조정하기
