### ISSUE TITLE
[FIX] 위치 권한 거부 시 비정상 종료 해결 및 위치 권한 팝업 플로우 변경

### ISSUE THREAD

**Issue by sxunea** [Runnect/Runnect-Android#292]
## 💡 Issue 
- 위치 권한 거부 시 종료 문제 해결
- 위치 권한 설정 팝업 추가

## 📝 todo
위치 권한 팝업 
- [x] 앱 진입 시
- [x] 내 위치 버튼 클릭 시 
- [x] 내가 그린 코스 시작하기 클릭 
- [x] 현재위치에서 시작하기 클릭시
- [x] 코스 이름 입력 후
