### ISSUE TITLE
[UI] 코스 발견 / 상세페이지 타 유저 프로필 조회

### ISSUE THREAD

**Issue by sxunea** [Runnect/Runnect-Android#300]
## 💡 Issue
코스 발견 상세페이지에서 프로필 클릭 시 해당 유저 프로필 조회 화면 구현

## 📝 todo

- [x] 프로필 조회 뷰 구현
  - [x] 툴바 제외하고 rv 포함 전체 스크롤 가능하게
- [x] 코스 상세페이지 변동사항 반영
