### ISSUE TITLE
[FEAT] 코스 발견 / 상세페이지 타 유저 프로필 조회

### ISSUE THREAD

**Issue by sxunea** [Runnect/Runnect-Android#303]
## 💡 Issue
코스 발견 상세페이지에서 프로필 클릭 시 해당 유저 프로필 조회 기능 구현

## 📝 todo

- [x] 상세페이지에서 프로필로 화면 전환 연결
- [x] 프로필 조회 getUserProfile API 연결해 기능 구현
- [x] 뒤로 가기 화면 전환 연결
- [x] 업로드한 코스 스크랩 createAndDeleteScrap API 연결해 기능 구현
- [x] 업로드한 코스 상세페이지 화면 전환 연결
