### ISSUE TITLE
[FEAT] 코스 발견 / 추천 코스 정렬 기능 

### ISSUE THREAD

**Issue by leeeha** [Runnect/Runnect-Android#307]
## 💡 Issue

- 최신순, 스크랩순으로 추천 코스 정렬 (디폴트는 최신순) 
- 코스 발견 화면을 리프레시 하면 정렬 기준도 최신순으로 초기화 

## 📝 todo
 
- [x] RecommendCourseViewHolder 에 정렬 버튼 클릭 리스너 정의 
- [x] 정렬 버튼 클릭 시, onSortButtonClick 람다식에 정렬 기준 전달 
  - RecommendCourseViewHolder → DiscoverMultiViewAdapter → DiscoverFragment → DiscoverViewModel 
- [x] 뷰모델에 현재 정렬 기준 저장 (다음 페이지 요청 시 필요) 
- [x] 정렬 버튼 누를 때마다 뷰모델에 있는 추천 코스 페이지 정보 초기화 (currentPageNumber, isEnd 속성) 
- [x] 뷰모델에서 현재 정렬 기준으로 서버한테 GET 요청 
- [x] 프래그먼트 옵저버에서 서버통신 Success 상태에 대한 처리 
    - DiscoverRecommendAdapter에서 submitList 호출 
- [x] 스크롤이 끝에 도달하면, 뷰모델에 저장된 정렬 기준으로 서버에 다음 페이지 요청
