### ISSUE TITLE
[Refactor] 내부 logic 연결

### ISSUE THREAD

**Issue by unam98** [Runnect/Runnect-Android#31]
## 💡 Issue

- 코스 보관함 상세페이지에서 시작하기 버튼을 누르면 RunActivity로 연결되고 이후의 flow들이 그대로 이어지게 하는 것
(이때 RunActivity의 logic은 CountDownActivity에서 넘어오는 data도 처리할 수 있게 작성되어야 함)
- 코스 발견에서 스크랩하면 보관함의 스크랩 탭에 나타나게 하기

## 📝 todo

- [x] RunActivity logic 수정 (DrawToRunData와 DetailToRunData가 모두 처리될 수 있어야 함)
- [x] 코스 발견 스크랩 <-> 보관함 스크랩 탭 연결 
- [x] 보관함 스크랩 서버 연결
- [x] 서로 헤더에 넣어주고 있는 machineID 통일
- [x] merge 시 편의를 위해 삭제하지 않았던 불필요한 파일들 file 삭제
- [x] DrawActivity에서 '보관함 가기' 터치로 넘어올 때 바텀네비게이션도 '보관함'으로 바뀌게 수정
- [x] '보관함'으로 넘어올 때 MainActivity logic 수정
