### ISSUE TITLE
[REFACTOR] 코스 발견 / 내가 그린 코스 업로드 리팩토링 

### ISSUE THREAD

**Issue by leeeha** [Runnect/Runnect-Android#319]
## 💡 Issue

내가 그린 코스를 조회하고 업로드 할 때의 코드를 리팩토링 합니다. 

## 📝 todo

- [x] UiStateV2 사용 
- [x] BaseResponse 사용 
- [x] 리사이클러뷰 감싸고 있는 네스티드 스크롤 뷰 삭제 
- [x] 아이템 클릭 리스너: 인터페이스 대신에 고차함수 사용
- [x] 데이터 클래스 자체를 번들 데이터로 넘기도록 (Parcelable) 
- [x] 한번 올린 코스는 재업로드 불가능하다는 문구 추가하기 
- [x] 리스트가 비어있는 경우에 대한 처리
