### ISSUE TITLE
[UI] 앱의 전반적인 UI 다듬기

### ISSUE THREAD

**Issue by unam98** [Runnect/Runnect-Android#33]
## 💡 Issue

기능 구현을 우선적으로 두느라 나중으로 미뤄뒀던 UI 작업들을 하려고 함

## 📝 todo

- [x] SearchActivity 리사이클러뷰 divider 넣기
- [x] 바텀네비게이션바 radius 문제 해결
- [x] 보관함 (내가 그린 코스, 스크랩 등)
- [x] 위치 오버레이 이미지 수정 (https://navermaps.github.io/android-map-sdk/guide-ko/5-5.html)
- [x] empty view visible 옵션 처리
