### ISSUE TITLE
[REFACTOR] 데이터 레이어 다른 계층 참조하지 않도록 순수하게 개선

### ISSUE THREAD

**Issue by sxunea** [Runnect/Runnect-Android#339]
## 💡 Issue
- 멀티모듈 이전 작업 전, 데이터 레이어가 다른 레이어를 참조하지 않도록 변경해 개선합니다
## 📝 todo

- [ ] Authenticator가 refresh Token 만료시 presentation 레이어를 참조하는 코드를 제거 
- [ ] AuthInterceptor에서 다음과 같은 것들을 관리 할 수 있도록
   - [ ] 헤더 부착
   - [ ] 액세스 토큰, 리프레시 토큰 관리
   - [ ] 액세스 토큰 만료 시 처리
   - [ ] 리프레시 토큰 만료 시 처리 
- [ ] presentation 레이어에서 만료 시 화면 이동을 수행할 수 있도록 구현
