### ISSUE TITLE
[Refactor] ViewModel에서 Flow를 사용할 수 있도록 수정

### ISSUE THREAD

**Issue by Donghyeon0915** [Runnect/Runnect-Android#342]
## 💡 Issue
- ViewModel에서 Flow를 사용할 수 있도록 CallAdapter 및 기타 코드 수정

## 📝 todo
- [ ] 1. CallAdapter 추가
- [ ] 2. BaseReseponse 제거 + ResponseInterceptor 추가
- [ ] 3. BaseViewModel + exceptionHandler 추가
- [ ] 4. ViewModel에서 flow 사용 가능하도록 변경
