### ISSUE TITLE
[REFACTOR] api 로직 수정 

### ISSUE THREAD

**Issue by unam98** [Runnect/Runnect-Android#344]
## 💡 Issue

callAdapter와 확장함수를 활용한 api 예외처리 및 코드 간결화
## 📝 todo

- [x] 출발지 주소 검색 API
- [x] 코스 생성 API
- [x] reverseGeoCoding API
- [x] 러닝 기록 업로드 API
- [x] 보관함 - 내가 그린 코스 API
- [x] 보관함 - 내가 스크랩한 코스 API
