### ISSUE TITLE
[Refactor] 개발자 모드 개선 & 네트워크 예외 처리 오류 수정 (FlowCallAdapter)

### ISSUE THREAD

**Issue by Donghyeon0915** [Runnect/Runnect-Android#348]
## 💡 Issue
- 개발자 모드 개선
- 네트워크 요청에서 예외가 발생하였을때 Flow의 Catch 연산자로 잡히지 않는 부분을 수정하였습니다.
   - [이슈 내용 참고](https://www.notion.so/runnectiosonboarding/24-04-24-dd61a29ab22449c085d433a84a9ecc0c?pvs=4)

## 📝 todo
- [x] 개발자 모드 디자인 수정
- [x] 서버 모드 변경시 자동으로 앱 재시작 되도록 수정
- [x] 토큰 공유하기 추가
- [x] 서버 상태 체크 로직 추가
- [x] FlowCallAdapter 추가
