### ISSUE TITLE
[Refactor] 페이지 연결

### ISSUE THREAD

**Issue by unam98** [Runnect/Runnect-Android#35]
## 💡 Issue

손 봐야 할 건 여전히 많지만 일단 여기 브랜치까지 작업하면 전체 뷰 및 logic 연결은 완료가 됨.
로그인은 소셜 로그인으로 새로 할 거라 나중에 함.
작업 끝나는대로 페이지 연결 -> 코드병합, 코드병합 -> develop 머지하면 됨.

## 📝 todo

- [x] 러닝 기록 upload 서버 연결
- [x] 코스 발견 - 추천 코스 상세페이지 시작하기 연결 (RunActivity 포함 이후의 flow도 그대로 따라지게 해야 함)
- [ ] 보관함 - 스크랩 코스 상세페이지 시작하기 연결 (RunActivity 포함 이후의 flow도 그대로 따라지게 해야 함)
- [x] 보관함 - 스크랩 하기 버튼 터치 시 코스 발견으로 이동 
- [x] 보관함 - 스크랩 하트 터치 시 스크랩 취소

## 💡 Check
상세페이지 시작하기 연결은 api가 수정될 여지가 있어서 나중에 서버, iOS랑 같이 얘기해보고 fix되면 그때 작업하기로 함
