### ISSUE TITLE
[Refactor] 로딩 뷰 추가 외 2건

### ISSUE THREAD

**Issue by unam98** [Runnect/Runnect-Android#39]
## 💡 Issue

0214 회의에서 정리한 작업

## 📝 todo

- [x] 서버 통신이 이루어지는 부분에 로딩 뷰 추가 
- [x] DrawActivity에서 서버통신이 완료된 후에 커스텀 다이얼로그 띄우기 (동기 처리)
- [x] 보관함-스크랩한 코스에서 하트 터치 시 스크랩 취소될 때 취소한 리사이클러뷰 item이 즉각적으로 삭제되게 하기
