### ISSUE TITLE
[Refactor] 로딩뷰추가외2건 브랜치 PR 피드백 반영 

### ISSUE THREAD

**Issue by unam98** [Runnect/Runnect-Android#42]
## 💡 Issue

로딩뷰추가외2건 브랜치 PR 피드백 반영 

## 📝 todo

- [x] 스크랩 전부 취소 시 empty view 안 뜨는 logic 수정 
- [x] createMbr에 로그 찍어서 상세한 원인 파악
- [x] SearchActivity에서 empty view에서 정상적인 검색결과가 조회되는 페이지 띄울 때 안 깜빡이게 logic 수정
