### ISSUE TITLE
[Refactor] Grid RecyclerView 크기 기기별 대응

### ISSUE THREAD

**Issue by Larry7939** [Runnect/Runnect-Android#46]
## 💡 Issue

Scalable Layout을 활용한 Grid RecyclerView 크기 기기별 대응
## 📝 todo

- [ ] 코스발견 - 불러오기 뷰
- [ ] 코스발견 - 검색 결과 뷰
- [ ] 마이페이지 - 목표보상 뷰
- [ ] 마이페이지 - 업로드한 코스 뷰
- [ ] 보관함 - 내가 그린 코스 뷰 및 스크랩 코스 뷰
