### ISSUE TITLE
QA 준비

### ISSUE THREAD

**Issue by unam98** [Runnect/Runnect-Android#50]
## 💡 Issue

QA 준비
## 📝 todo

- [x] 페이지 간 애니메이션 적용 
- [ ] 활동 기록 사진 모서리 둥글게
- [ ] 평균 페이스 로직 수정
- [x] 활동 기록 리사이클러뷰 텍스트 정렬
