### ISSUE TITLE
QA_1차 피드백 반영

### ISSUE THREAD

**Issue by unam98** [Runnect/Runnect-Android#56]
## 💡 Issue

0305 기디클 오프라인 회의 때 받은 피드백 반영
## 📝 todo

- [x] SearchActivity 우측 상단에 돋보기 버튼 추가
- [x] DepartureActivity랑 DrawActivity랑 합치고 iOS 따라서 애니메이션 적용
- [x] DrawActivity에서 터치값 아무것도 없을 때 완성/백 버튼 비활성화 및 불투명 처리
- [ ] 코스 완성하기 커스텀 Dialog에 쓰이는 일러스트가 예전 버전이라 새로운 걸로 바꾸기
- [ ] 디자인 파트원분들한테 svg 그대로 받아서 깨지는 이미지들 다 갈아끼우기
- [x] RunActivity에서 노드마다 하얀색 원 찍히도록 logic 수정
- [x] 타이머 시간 형식을 00:00:00으로 바꾸기
- [ ] 평균페이스 logic 및 형식 수정
- [x] RunActivity로 넘어오는 모든 경우에 카운트다운 애니메이션 적용
- [ ] EndRunActivity에서 뒤로가기 눌렀을 때 각각의 메인뷰로 돌아가게하기
- [x] 로딩바 색상 회색으로 바꾸기
- [x] 보관함-내가그린코스 제목 수정 (ex. 중구 서울 -> 서울 중구)
- [x] 마커 20개 제한 추가
- [x] 기록 업로드 제목 글자수 20자 제한 적용
- [ ] 보관함 하위에 Fragment를 2개 두고 각각의 tab으로 넘어갈 때마다 서버통신이 이루어지니까 지연이 발생하는데 뷰페이저로 바꾸기
- [x] font Bold 적용 안 되는 거 적용해놓기
