### ISSUE TITLE
이미지 로딩 딜레이 개선

### ISSUE THREAD

**Issue by Larry7939** [Runnect/Runnect-Android#57]
## 💡 Issue

이미지 로딩 딜레이 개선
한꺼번에 많은 썸네일 이미지를 보여주는 grid recycler view 위주로 개선
Coil -> Glide Migration 및 픽셀 포맷 변경 ARGB_8888 -> RGB_565
Glide thumbnail 추가
## 📝 todo

- [x] 추천 코스
- [x] 마이페이지 - 목표 보상(색 표현을 위해 ARGB_8888 유지)
- [x] 마이페이지 - 활동 기록
- [x] 마이페이지 - 업로드한 코스
