### ISSUE TITLE
릴리즈 전까지 할 작업

### ISSUE THREAD

**Issue by unam98** [Runnect/Runnect-Android#62]
## 💡 Issue

지훈이가 불러오기 리사이클러뷰 selection 문제 해결하고 소셜로그인을 해주기로 함.
나는 곧 준비될 코스 수정/삭제 디자인 및 서버 연결 작업이랑 1차 QA 때 피드백 받은 내용을 마저 반영하기로 함.

(03/13)
- 보관함-내가 그린 코스 UI 바인딩을 dto랑 바로 연결해주니까 '서울 마포구' 이런 식으로 띄어쓰기가 안 됨. 
뷰모델에 저장해놓고 가져오는 식이면 가공을 해줄 수 있는데 xml 단에서는 안 되는 것 같음.
dto랑 바로 연결지어주는 logic들 다 뷰모델에 저장 후 data binding을 쓸 수 있게 수정이 필요해보임  
- 업로드한 코스 등 gridLayout을 쓰는 부분에서 제목을 길게 적으면 잘려나옴.  '...' 이런 걸로 처리하거나 최대 text 길이 제한을 걸거나 해야 할 것 같음. 

## 📝 todo

- [x] 코스 수정/삭제 UI 개발 및 서버 연결
- [x] 이미지 깨지는 문제 해결
- [x] 평균 페이스 logic 및 형식 수정
- [ ] EndRunActivity에서 뒤로가기 눌렀을 때 각각의 메인뷰로 돌아가게하기
- [x] 구글 소셜 로그인 테스트
- [ ] 상세페이지 이미지 맵 객체로 바꾸기 (서버에서 path data까지 보내줘야 가능)
- [x] 스크랩 상세페이지 -> CountDownActivity intent 전환 (서버에서 path data까지 보내줘야 가능)
