### ISSUE TITLE
릴리즈마감/우남

### ISSUE THREAD

**Issue by unam98** [Runnect/Runnect-Android#64]
## 💡 Issue

'릴리즈 전 작업' 브랜치를 merge함에 따라 이와 연결돼있는 Issue를 closed하고 새 브랜치, Issue를 만들었음.
온보딩/자체 회원가입 및 로그인 기능 역할 분배가 어떻게 될지 모르겠지만 당장은 아래의 것들만 다 하면
이번 릴리즈까지 내 할 것들은 다 한 것

## 📝 todo

- [x] 스크랩 코스 상세페이지 - 신고하기 기능 웹뷰 구현
- [x] 보관함/내가 그린 코스 - item 중복 선택 기능 구현
- [x] 보관함/내가 그린 코스 - 코스 삭제 기능 구현
- [x] 내가 그린 코스 상세페이지 - 코스 삭제 기능 구현
- [x] 코스 그리기/메인뷰 - 상단 가이드 뷰 추가
- [x] 코스 그리기/코스만드는중 - 상단 가이드 뷰 추가
- [x] 카운트다운 애니메이션 밑 textView 흔들리는 이슈 해결
- [x] 이미지 깨지는 이슈 해결
- [x] 러닝 기록 페이지 
- [ ] EndRunActivity에서 뒤로가기 눌렀을 때 각각의 메인뷰로 돌아가게하기
- [x] 스크랩 상세페이지 -> CountDownActivity intent 전환 (서버에서 path data까지 보내줘야 가능)
- [x] 상세페이지 이미지 맵 객체로 바꾸기 (서버에서 path data까지 보내줘야 가능) - 확정 여부 확인 필요
- [x] 구글 소셜 로그인 코드 정리
