### ISSUE TITLE
[UI] 마이페이지 업로드 코스

### ISSUE THREAD

**Issue by unam98** [Runnect/Runnect-Android#7]
## 💡 Issue

![mypage_upload](https://user-images.githubusercontent.com/89737271/209981136-6e1081ca-6099-4615-8bc2-a4fb0fb1fc87.PNG)

## 📝 todo

- [x] 리사이클러뷰 item 디자인
- [ ] item 간격 조절
- [ ] style(textSize, font, textColor 등)

## 메모
reward 페이지에서도 gridLayout 간격 조절을 못했는데 구글링을 계속해본 결과,
itemDecoration이라는 걸 사용해야 하며 xml 상에서 조절은 못한다는 결론을 내림.
추후에 디자인 asset 다 나오면 함께 리팩토링할 예정.
